["0000:03:00.0"]
mode = "trapezoidal"
temp_mode = "avg"
point = [
  [30, 0],
  [90, 100]
]

["0000:04:00.0"]
mode = "ladder"
temp_mode = "edge"
point = [
  [30, 0],
  [40, 20],
  [50, 30],
  [60, 50],
  [80, 80],
]
